services:
  api:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    command: yarn run start:dev api
    env_file:
      - apps/server/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - ./apps/client:/app
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://api:3000/api
    command: yarn start